### ISSUE TITLE
Fonts for Russian language

### ISSUE THREAD

**Issue by FBNikita** [kleientertainment/Forge2018StatsPage#7]
Hey. Writes one of the developers of the Russian localization mode. We have fonts with Russian characters added. Can you embed them somehow when choosing the Russian version of the site? Russian-speaking players would be pleased to see, instead of standard text fonts, a font that is close to the original. Thank.

**Comment by ricardjorg** [comment]
Hi @FBNikita! That's a great idea, and certainly feasible. Can you send me these font files? If so, I'll test them on the page, and if they work well, I can put them live. Tell me as well who made the fonts, so that I include that in the Russian translation's credits.

**Comment by FBNikita** [comment]
Here is a link to it. Was supplement by me
https://drive.google.com/file/d/10mBUPQcXBWWJHxCguxRxLEUwOG9LEMlr/view

**Comment by ricardjorg** [comment]
@FBNikita The font seems fine. Are you going to submit a pull-request with your translation?

**Comment by FBNikita** [comment]
> @FBNikita The font seems fine. Are you going to submit a pull-request with your translation?

Yes, now I will translate and send. It's just that I, in parallel with sending the font, still raided with my guild to the World of Warcraft: D

**Comment by ricardjorg** [comment]
@FBNikita Haha, no rush! 👍

**Comment by FBNikita** [comment]
**Crystalized Magma Chamber** and **Blacksmith's Edge**
Can I find out what it is and how it looks? It is necessary for proper translation.

**Comment by ricardjorg** [comment]
@FBNikita Sorry, those items/creatures haven't been unlocked yet. You'll have to base your translation on the English names. You can always improve the translation later, after they're unlocked. I think that's what everyone's planning.

**Comment by FBNikita** [comment]
I made Pull request. For me, not knowing js, was difficult to decline time)

**Comment by ricardjorg** [comment]
@FBNikita The translation and font are live! Thank you!
